#!/usr/bin/env python3
"""Generates every icon and store image from the one mark defined below.

The mark is a page with text lines beside a speech waveform, drawn on the 108-unit
adaptive-icon canvas (the visible area is the centred 72, the safe zone a 66 circle).
Vector outputs are written from the shapes directly; PNGs are rasterised with Pillow
at 4x and downsampled, so no SVG toolchain is needed. Run it after changing the mark:

    python3 scripts/gen-brand.py

Needs Pillow and the Noto Sans fonts (OFL) for the feature graphic. The outputs are
committed, so the app and F-Droid builds never run this.
"""
import math
import os
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, 'android/app/src/main/res')
LISTING = os.path.join(ROOT, 'fastlane/metadata/android/en-US')
BRAND = os.path.join(ROOT, 'assets/brand')

INK = '#1d2b4f'
PAPER = '#f7f4ec'
FOLD = '#d6cfbd'
# The reader's sentence highlight (src/ui/ui.ts), so the icon and the reader share a colour.
YELLOW = '#ffe680'

PAGE_X0, PAGE_X1, PAGE_Y0, PAGE_Y1, FOLD_SIZE = 26, 50, 34, 74, 9
LINE_W = 3
LINES = [(48, 14), (55, 14), (62, 10), (69, 13)]  # (y, length)
BAR_W = 3.5
BARS = [(60, 6), (65, 14), (70, 22), (75, 12), (80, 6)]  # (x, height), centred on y=54
BAR_CY = 54


def page_points():
    x0, x1, y0, y1, f = PAGE_X0, PAGE_X1, PAGE_Y0, PAGE_Y1, FOLD_SIZE
    return [(x0, y0), (x1 - f, y0), (x1, y0 + f), (x1, y1), (x0, y1)]


def fold_points():
    x1, y0, f = PAGE_X1, PAGE_Y0, FOLD_SIZE
    return [(x1 - f, y0), (x1 - f, y0 + f), (x1, y0 + f)]


def line_segments():
    return [((PAGE_X0 + 5, y), (PAGE_X0 + 5 + n, y)) for y, n in LINES]


def bar_segments():
    return [((x, BAR_CY - h / 2), (x, BAR_CY + h / 2)) for x, h in BARS]


# ---------------------------------------------------------------- vector output

def fmt(v):
    return ('%.3f' % v).rstrip('0').rstrip('.')


def poly_path(pts):
    return 'M' + ' L'.join('%s,%s' % (fmt(x), fmt(y)) for x, y in pts) + ' Z'


def seg_path(a, b):
    return 'M%s,%s L%s,%s' % (fmt(a[0]), fmt(a[1]), fmt(b[0]), fmt(b[1]))


def stadium_path(a, b, w):
    """A horizontal round-capped segment as a closed outline, for even-odd cut-outs."""
    r = w / 2
    (x0, y), (x1, _) = a, b
    return ('M%s,%s L%s,%s A%s,%s 0 0,1 %s,%s L%s,%s A%s,%s 0 0,1 %s,%s Z' % (
        fmt(x0), fmt(y - r), fmt(x1), fmt(y - r), fmt(r), fmt(r), fmt(x1), fmt(y + r),
        fmt(x0), fmt(y + r), fmt(r), fmt(r), fmt(x0), fmt(y - r)))


def vector(width_dp, viewport, body):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by scripts/gen-brand.py; edit the script, not this file. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="%sdp" android:height="%sdp"\n'
            '    android:viewportWidth="%s" android:viewportHeight="%s">\n%s</vector>\n'
            % (width_dp, width_dp, viewport, viewport, body))


def fill(d, color, even_odd=False):
    rule = '\n        android:fillType="evenOdd"' if even_odd else ''
    return ('    <path android:fillColor="%s"%s\n        android:pathData="%s" />\n'
            % (color, rule, d))


def stroke(d, color, w):
    return ('    <path android:strokeColor="%s" android:strokeWidth="%s"\n'
            '        android:strokeLineCap="round"\n        android:pathData="%s" />\n'
            % (color, fmt(w), d))


def foreground_xml():
    body = fill(poly_path(page_points()), PAPER) + fill(poly_path(fold_points()), FOLD)
    body += ''.join(stroke(seg_path(a, b), INK, LINE_W) for a, b in line_segments())
    body += ''.join(stroke(seg_path(a, b), YELLOW, BAR_W) for a, b in bar_segments())
    return vector(108, 108, body)


def mono_body(color):
    # One colour only: the text lines become holes in the page, so it still reads as a page.
    page = poly_path(page_points()) + ' ' + ' '.join(
        stadium_path(a, b, LINE_W) for a, b in line_segments())
    body = fill(page, color, even_odd=True)
    body += ''.join(stroke(seg_path(a, b), color, BAR_W) for a, b in bar_segments())
    return body


def monochrome_xml():
    return vector(108, 108, mono_body('#ffffff'))


def notification_xml():
    # Status-bar icons are 24dp and alpha-only. Scale the mark's bounding box to fit the
    # 24-unit viewport with a 1-unit margin, centred.
    x0, x1 = PAGE_X0, BARS[-1][0] + BAR_W / 2
    y0, y1 = PAGE_Y0, PAGE_Y1
    s = 22 / max(x1 - x0, y1 - y0)
    tx = (24 - (x1 - x0) * s) / 2 - x0 * s
    ty = (24 - (y1 - y0) * s) / 2 - y0 * s
    body = ('  <group android:scaleX="%s" android:scaleY="%s"\n'
            '      android:translateX="%s" android:translateY="%s">\n%s  </group>\n'
            % (fmt(s), fmt(s), fmt(tx), fmt(ty), mono_body('#ffffff')))
    return vector(24, 24, body)


ADAPTIVE = ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by scripts/gen-brand.py; edit the script, not this file. -->\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@color/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')

COLOR_XML = ('<?xml version="1.0" encoding="utf-8"?>\n'
             '<!-- Generated by scripts/gen-brand.py; edit the script, not this file. -->\n'
             '<resources>\n    <color name="ic_launcher_background">%s</color>\n</resources>\n'
             % INK)


def svg():
    """The visible 72-unit square with rounded corners, for the README and anywhere else."""
    parts = ['<rect x="18" y="18" width="72" height="72" rx="16" fill="%s"/>' % INK,
             '<path d="%s" fill="%s"/>' % (poly_path(page_points()), PAPER),
             '<path d="%s" fill="%s"/>' % (poly_path(fold_points()), FOLD)]
    for a, b in line_segments():
        parts.append('<path d="%s" stroke="%s" stroke-width="%s" stroke-linecap="round"/>'
                     % (seg_path(a, b), INK, fmt(LINE_W)))
    for a, b in bar_segments():
        parts.append('<path d="%s" stroke="%s" stroke-width="%s" stroke-linecap="round"/>'
                     % (seg_path(a, b), YELLOW, fmt(BAR_W)))
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="512" '
            'height="512">\n<!-- Generated by scripts/gen-brand.py -->\n  %s\n</svg>\n'
            % '\n  '.join(parts))


# ---------------------------------------------------------------- raster output

SS = 4  # supersampling factor


def render_layer(px, background=True):
    """The full 108-unit layer (background + foreground) at px x px."""
    big = px * SS
    s = big / 108
    im = Image.new('RGBA', (big, big), INK if background else (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    P = lambda pts: [(x * s, y * s) for x, y in pts]
    d.polygon(P(page_points()), fill=PAPER)
    d.polygon(P(fold_points()), fill=FOLD)

    def seg(a, b, w, c):
        d.line(P([a, b]), fill=c, width=round(w * s))
        r = w * s / 2
        for x, y in (a, b):
            d.ellipse([x * s - r, y * s - r, x * s + r, y * s + r], fill=c)

    for a, b in line_segments():
        seg(a, b, LINE_W, INK)
    for a, b in bar_segments():
        seg(a, b, BAR_W, YELLOW)
    return im.resize((px, px), Image.LANCZOS)


def masked_icon(px, shape):
    """The visible 72/108 of the layer, masked to a circle or a rounded square."""
    full = round(px * 108 / 72)
    layer = render_layer(full)
    off = (full - px) // 2
    icon = layer.crop((off, off, off + px, off + px))
    mask = Image.new('L', (px * SS, px * SS), 0)
    md = ImageDraw.Draw(mask)
    if shape == 'circle':
        md.ellipse([0, 0, px * SS - 1, px * SS - 1], fill=255)
    else:
        md.rounded_rectangle([0, 0, px * SS - 1, px * SS - 1], radius=px * SS * 16 // 72, fill=255)
    mask = mask.resize((px, px), Image.LANCZOS)
    out = Image.new('RGBA', (px, px), (0, 0, 0, 0))
    out.paste(icon, (0, 0), mask)
    return out


FONT_DIR = '/usr/share/fonts/truetype/noto'


def font(name, size):
    path = os.path.join(FONT_DIR, name)
    if not os.path.exists(path):
        sys.exit('missing font %s (install fonts-noto-core)' % path)
    return ImageFont.truetype(path, size)


def feature_graphic():
    """1024x500, F-Droid's featureGraphic: the icon and the name, tagline below."""
    w, h = 1024, 500
    im = Image.new('RGBA', (w * SS, h * SS), INK)
    d = ImageDraw.Draw(im)
    icon = masked_icon(300 * SS, 'square')
    # The icon's background matches the canvas, so the mark sits on it without an edge.
    im.paste(icon, (70 * SS, 100 * SS), icon)
    title = font('NotoSans-Bold.ttf', 76 * SS)
    tag = font('NotoSans-Regular.ttf', 34 * SS)
    tx = 420 * SS
    d.text((tx, 150 * SS), 'Read Me', font=title, fill=PAPER)
    d.text((tx, 238 * SS), 'Offline', font=title, fill=YELLOW)
    d.text((tx, 350 * SS), 'Shared articles and text, read aloud.', font=tag, fill=PAPER)
    d.text((tx, 395 * SS), 'On-device voices. No cloud TTS, no tracking.', font=tag, fill='#aab3c8')
    return im.resize((w, h), Image.LANCZOS).convert('RGB')


# ---------------------------------------------------------------- main

DENSITIES = {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)
    print(os.path.relpath(path, ROOT))


def save(im, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    im.save(path, optimize=True)
    print(os.path.relpath(path, ROOT))


def main():
    write(os.path.join(RES, 'drawable/ic_launcher_foreground.xml'), foreground_xml())
    write(os.path.join(RES, 'drawable/ic_launcher_monochrome.xml'), monochrome_xml())
    write(os.path.join(RES, 'drawable/ic_stat_readme.xml'), notification_xml())
    write(os.path.join(RES, 'values/ic_launcher_background.xml'), COLOR_XML)
    write(os.path.join(RES, 'mipmap-anydpi-v26/ic_launcher.xml'), ADAPTIVE)
    write(os.path.join(RES, 'mipmap-anydpi-v26/ic_launcher_round.xml'), ADAPTIVE)
    # minSdk 24: API 24-25 have no adaptive icons and use these.
    for dens, px in DENSITIES.items():
        save(masked_icon(px, 'square'), os.path.join(RES, 'mipmap-%s/ic_launcher.png' % dens))
        save(masked_icon(px, 'circle'), os.path.join(RES, 'mipmap-%s/ic_launcher_round.png' % dens))
    write(os.path.join(BRAND, 'icon.svg'), svg())
    save(masked_icon(512, 'square'), os.path.join(LISTING, 'images/icon.png'))
    save(feature_graphic(), os.path.join(LISTING, 'images/featureGraphic.png'))


if __name__ == '__main__':
    main()
