package io.loopstring.readme.spike

import android.app.ActivityManager
import android.content.Context
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.os.SystemClock
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import android.util.Log
import org.json.JSONObject
import java.io.BufferedInputStream
import java.io.BufferedOutputStream
import java.io.File
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.net.InetAddress
import java.net.ServerSocket
import java.net.Socket
import java.util.Locale
import java.util.concurrent.CountDownLatch
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit

/**
 * SPIKE-01 only: the smallest loopback bridge that answers "does synthesis keep working
 * while Read Me is backgrounded and Obsidian is foreground, under this FGS type?".
 * Construct on the main thread. Throws BindException if [port] is in use. The [token] is
 * generated by the calling script and is never logged (AGENTS.md 4).
 */
class SpikeBridge(context: Context, private val token: String, private val port: Int = 8787) {
  private val cacheDir = context.cacheDir
  private val handler = Handler(Looper.getMainLooper())
  private val pool = Executors.newFixedThreadPool(4)
  private val synthLock = Any()
  private var seq = 0
  @Volatile private var ttsReady = false
  @Volatile private var pendingId: String? = null
  @Volatile private var latch: CountDownLatch? = null
  @Volatile private var failed = false
  // R-M12: explicit IPv4 loopback; getLoopbackAddress() returned ::1 on Android 17.
  private val server = ServerSocket(port, 16, InetAddress.getByAddress(byteArrayOf(127, 0, 0, 1)))
  // Deferred like GapProbe: onInit may run inside the TextToSpeech constructor.
  private val tts: TextToSpeech =
      TextToSpeech(context.applicationContext) { status -> handler.post { onReady(status) } }

  init {
    Thread(::acceptLoop, "spike-bridge").start()
  }

  fun close() {
    try { server.close() } catch (_: IOException) {}
    pool.shutdownNow()
    handler.removeCallbacksAndMessages(null)
    tts.shutdown()
  }

  private fun onReady(status: Int) {
    if (status != TextToSpeech.SUCCESS) return
    tts.setLanguage(Locale.US)
    tts.setOnUtteranceProgressListener(Listener())
    ttsReady = true
  }

  private inner class Listener : UtteranceProgressListener() {
    override fun onStart(id: String) {}
    override fun onDone(id: String) {
      if (id == pendingId) latch?.countDown()
    }
    @Deprecated("Deprecated in Java")
    override fun onError(id: String) {
      if (id == pendingId) {
        failed = true
        latch?.countDown()
      }
    }
    override fun onError(id: String, code: Int) {
      @Suppress("DEPRECATION") onError(id)
    }
  }

  private fun acceptLoop() {
    while (!server.isClosed) {
      val s = try { server.accept() } catch (_: IOException) { break }
      try {
        pool.execute { serve(s) }
      } catch (_: java.util.concurrent.RejectedExecutionException) {
        s.close()   // close() raced an accept; the bridge is shutting down
        break
      }
    }
  }

  private fun serve(s: Socket) {
    val t0 = SystemClock.elapsedRealtime()
    var method = "?"
    var route = "?"
    var status = 0
    try {
      s.use {
        it.soTimeout = 10_000
        val input = BufferedInputStream(it.getInputStream())
        val out = BufferedOutputStream(it.getOutputStream())
        val head = readHead(input)
        if (head == null) {
          status = send(out, 431, null, "text/plain", "headers too large".toByteArray())
          return@use
        }
        val lines = head.split("\r\n")
        val parts = lines.first().split(" ")
        if (parts.size < 2) {
          status = send(out, 400, null, "text/plain", "bad request".toByteArray())
          return@use
        }
        method = parts[0]
        val path = parts[1].substringBefore('?')
        val query = parts[1].substringAfter('?', "")
        route = if (path == "/health" || path == "/synthesize") path else "other"
        val headers = lines.drop(1).mapNotNull { l ->
          val i = l.indexOf(':')
          if (i <= 0) null else l.substring(0, i).trim().lowercase(Locale.ROOT) to l.substring(i + 1).trim()
        }.toMap()
        val origin = headers["origin"]
        status = when {
          method == "OPTIONS" -> send(out, 204, origin, "text/plain", ByteArray(0))
          method == "GET" && path == "/health" -> send(out, 200, origin, "application/json",
              JSONObject().put("ok", true).put("ttsReady", ttsReady).put("port", port).toString().toByteArray())
          method == "POST" && path == "/synthesize" -> synthesize(input, out, headers, query, origin)
          else -> send(out, 404, origin, "text/plain", "not found".toByteArray())
        }
      }
    } catch (t: Throwable) {
      // R-M12: Throwable, so one connection can never take the service down. Class name only.
      Log.w(SpikeService.TAG, "conn: ${t.javaClass.simpleName}")
    }
    // The method is client-controlled; log only a fixed token (AGENTS.md 1).
    val loggedMethod = if (method in KNOWN_METHODS) method else "other"
    SpikeService.report("BRIDGE", JSONObject().put("method", loggedMethod).put("route", route).put("status", status)
        .put("ms", SystemClock.elapsedRealtime() - t0).put("importance", importance()))
  }

  private fun readHead(input: InputStream): String? {
    val buf = StringBuilder()
    while (true) {
      val c = input.read()
      if (c == -1) return buf.toString()
      buf.append(c.toChar())
      if (buf.length > MAX_HEAD) return null
      if (buf.endsWith("\r\n\r\n")) return buf.substring(0, buf.length - 4)
    }
  }

  private fun synthesize(
      input: InputStream,
      out: OutputStream,
      headers: Map<String, String>,
      query: String,
      origin: String?,
  ): Int {
    // Token before body (R-M12).
    if (headers["authorization"] != "Bearer $token") return send(out, 401, origin, "text/plain", "unauthorized".toByteArray())
    // Rate is applied once, here, by the engine (AGENTS.md 9). Default 1.0, never the system default.
    val rateParam = query.split('&').firstOrNull { it.startsWith("rate=") }?.removePrefix("rate=")
    val rate = if (rateParam == null) 1.0f else rateParam.toFloatOrNull()?.takeIf { it in 0.5f..4.0f }
        ?: return send(out, 400, origin, "text/plain", "bad rate".toByteArray())
    val len = headers["content-length"]?.toIntOrNull() ?: return send(out, 400, origin, "text/plain", "bad content-length".toByteArray())
    if (len < 0) return send(out, 400, origin, "text/plain", "bad content-length".toByteArray())
    if (len > MAX_BODY) return send(out, 413, origin, "text/plain", "body too large".toByteArray())
    val body = ByteArray(len)
    var got = 0
    while (got < len) {
      val k = input.read(body, got, len - got)
      if (k < 0) break
      got += k
    }
    if (got != len) return send(out, 400, origin, "text/plain", "short body".toByteArray())
    if (!ttsReady) return send(out, 503, origin, "text/plain", "tts not ready".toByteArray())
    synchronized(synthLock) {
      val id = "b${seq++}"
      val f = File(cacheDir, "spike-bridge-$id.wav")
      try {
        val l = CountDownLatch(1)
        latch = l
        pendingId = id
        failed = false
        tts.setSpeechRate(rate)
        val t0 = SystemClock.elapsedRealtime()
        if (tts.synthesizeToFile(String(body, Charsets.UTF_8), Bundle(), f, id) != TextToSpeech.SUCCESS) {
          return send(out, 500, origin, "text/plain", "synthesize rejected".toByteArray())
        }
        if (!l.await(60, TimeUnit.SECONDS) || failed || !f.exists()) {
          return send(out, 500, origin, "text/plain", "synthesis failed".toByteArray())
        }
        val ms = SystemClock.elapsedRealtime() - t0
        return send(out, 200, origin, "audio/wav", f.readBytes(), "X-Synth-Ms: $ms\r\nX-Rate: $rate\r\n")
      } finally {
        f.delete()
      }
    }
  }

  private fun send(out: OutputStream, code: Int, origin: String?, type: String, body: ByteArray, extra: String = ""): Int {
    val cors = if (origin == ALLOWED_ORIGIN) {
      "Access-Control-Allow-Origin: $ALLOWED_ORIGIN\r\n" +
          "Access-Control-Allow-Methods: GET, POST\r\n" +
          "Access-Control-Allow-Headers: Authorization, Content-Type\r\n" +
          "Access-Control-Expose-Headers: X-Synth-Ms, X-Rate\r\n"
    } else {
      ""
    }
    val head = "HTTP/1.1 $code ${REASONS[code] ?: "Status"}\r\n" +
        "Content-Type: $type\r\nContent-Length: ${body.size}\r\nConnection: close\r\n$cors$extra\r\n"
    out.write(head.toByteArray(Charsets.UTF_8))
    out.write(body)
    out.flush()
    return code
  }

  private fun importance(): Int =
      ActivityManager.RunningAppProcessInfo().also { ActivityManager.getMyMemoryState(it) }.importance

  companion object {
    private const val MAX_HEAD = 16 * 1024
    private const val MAX_BODY = 64 * 1024
    private const val ALLOWED_ORIGIN = "http://localhost"
    private val KNOWN_METHODS = setOf("GET", "POST", "OPTIONS")
    private val REASONS = mapOf(
        200 to "OK", 204 to "No Content", 400 to "Bad Request", 401 to "Unauthorized",
        404 to "Not Found", 413 to "Payload Too Large", 431 to "Request Header Fields Too Large",
        500 to "Internal Server Error", 503 to "Service Unavailable",
    )
  }
}
