/// <reference types="node" />
// R-S05 / ADR 0011: continuous play segments the next item in Kotlin (playback/Segmenter.kt),
// with no JS. This test pins the TS fallback segmenter, remapPosition, sentenceIndexAt and
// plan() to a committed golden file; SegmenterParityTest.kt runs the Kotlin port on the same
// file and must produce identical offsets. A change to the TS side fails here until the golden
// is regenerated (UPDATE_PARITY=1 npx jest segmentParity), and then fails in Kotlin until the
// port follows.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { extractArticle } from '../src/extract/extract';
import { splitSharedText } from '../src/intake/paragraphs';
import { plan } from '../src/library/playback';
import { segment } from '../src/segment/segment';
import type { Position } from '../src/types';

jest.mock('../src/native/NativeReadMeSpeech', () => ({ __esModule: true, default: {} }));

const GOLDEN = join(__dirname, 'fixtures/segment-parity.json');
const fixture = (p: string) => readFileSync(join(__dirname, 'fixtures', p), 'utf8');
// The Gutenberg page is 852 KB; its first paragraphs are enough and keep the golden small.
const MAX_PARAGRAPHS = 400;

type Case = { name: string; paragraphs: string[] };

function cases(): Case[] {
  const page = (name: string) =>
    extractArticle(fixture(`pages/${name}`)).paragraphs.slice(0, MAX_PARAGRAPHS).map(p => p.text);
  return [
    { name: 'segmentation-mixed', paragraphs: splitSharedText(fixture('text/segmentation-mixed.txt')).map(p => p.text) },
    { name: 'weather-gov-flood', paragraphs: page('weather-gov-flood.html') },
    { name: 'weather-gov-lightning', paragraphs: page('weather-gov-lightning.html') },
    { name: 'gutenberg-1342', paragraphs: page('gutenberg-1342.html') },
    {
      // The edges of segment.test.ts: the cap, clause and hard cuts, surrogates, odd spaces.
      name: 'edges',
      paragraphs: [
        'Dr. Smith went to Washington. He arrived at 3 p.m. on Jan. 5, 2026! Did it work? "Yes," she said. The U.S. economy grew 2.5% last year.',
        'He said "Stop." Then left. J. R. R. Tolkien wrote it. See fig. 3 now. I said no. Then went. No. 5 is here.',
        'Wait... what happened? Nothing. etc. And so on. Mt. Everest is high. vs. Them.',
        'word '.repeat(120).trim() + '.',
        'a'.repeat(390) + ', ' + 'b'.repeat(100) + '.',
        'x'.repeat(1000),
        'y'.repeat(399) + '😀' + 'z'.repeat(50),
        '     Leading and trailing spaces.  Then　more. Next line. ﻿BOM start.  ',
        '   ',
        'Straße. ß is lower. ǅ titlecase. ﬁ ligature. ΐ end. İstanbul. ı dotless.',
        '今日は晴れです。明日は雨です。本当ですか？はい！',
        'Ends with closers.)" Next one!» Another?” Yes.',
        '',
        'One sentence only',
      ],
    },
  ];
}

const CUT_VARIANTS = (n: number): number[][] => [
  [],
  Array.from({ length: n }, (_, i) => i).filter(i => i % 3 === 1),
  Array.from({ length: n }, (_, i) => i),
];

function positions(paragraphs: string[]): (Position | null)[] {
  const all = segment(paragraphs.map(text => ({ kind: 'p', text })));
  const step = Math.max(1, Math.floor(all.length / 7));
  const out: (Position | null)[] = [null];
  for (let i = 0; i < all.length; i += step) {
    const s = all[i];
    out.push(
      { paragraphIndex: s.paragraphIndex, charOffset: s.start },
      { paragraphIndex: s.paragraphIndex, charOffset: s.start + 1 },
      { paragraphIndex: s.paragraphIndex, charOffset: s.end },
    );
  }
  out.push(
    { paragraphIndex: paragraphs.length - 1, charOffset: 1_000_000 },
    { paragraphIndex: 1, charOffset: 3 },
    { paragraphIndex: paragraphs.length + 2, charOffset: 0 },
    { paragraphIndex: -1, charOffset: 0 },
  );
  return out;
}

function golden() {
  return {
    note: 'Generated by __tests__/segmentParity.test.ts (UPDATE_PARITY=1). Read by SegmenterParityTest.kt.',
    cases: cases().map(c => {
      const paras = c.paragraphs.map(text => ({ kind: 'p' as const, text }));
      const saved = positions(c.paragraphs);
      return {
        name: c.name,
        paragraphs: c.paragraphs,
        saved: saved.map(p => (p === null ? null : [p.paragraphIndex, p.charOffset])),
        variants: CUT_VARIANTS(c.paragraphs.length).map(cuts => ({
          cuts,
          sentences: segment(paras, new Set(cuts), { mode: 'fallback' }).map(s => [s.paragraphIndex, s.start, s.end]),
          plans: saved.map(p => {
            const r = plan(paras, cuts, p, { mode: 'fallback' });
            return r === null ? null : [r.startIndex, r.pastEnd];
          }),
        })),
      };
    }),
  };
}

test('the committed parity golden matches the TS segmenter, remap and plan', () => {
  const now = golden();
  if (process.env.UPDATE_PARITY === '1') writeFileSync(GOLDEN, JSON.stringify(now) + '\n');
  expect(JSON.parse(readFileSync(GOLDEN, 'utf8'))).toEqual(now);
});
